baseURL = "https://hkiang01.github.io"
languageCode = "en-us"
title = "Some reading materal"
googleAnalytics = "UA-180981920-1"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github"
identifier = "ds"
url = "https://github.com/hkiang01"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> LinkedIn"
url = "https://www.linkedin.com/in/harrison-kiang-ba737568/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fab fa-twitter'></i> Twitter"
url = "https://twitter.com/hkiang01/"
weight = 20
